controller_list:
  - name: fake_arm_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_gripper_left
      - joint_gripper_right
initial:  # Define initial robot poses per group
  - group: arm_controller
    pose: home
  - group: hand
    pose: open